spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev01?currentSchema=public
    username: dev01
    password: dev01
    hikari:
      # Default: 30000 (30 seconds)
      connection-timeout: 60000
      connection-test-query: SELECT 1
      # Default: same as maximumPoolSize
      minimum-idle: 50
      # Default: 10
      maximum-pool-size: 500
      auto-commit: false
  # hotRestart有効化
  devtools:
    restart:
      enabled: true

doma:
  dialect: postgres
  # SQLファイルをキャッシュする
  sql-file-repository: greedy_cache
  # バルクインサート・アップデートのサイズ
  batch-size: 1000

server:
  port: 8082
  servlet:
    session:
      # イントラネット利用を想定
      timeout: 60m
    context-path: /zeus

keel:
  transaction:
    token:
      # すべてのリクエストパスが2重送信防止対象
      path-patterns: /**





